customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
  - key: "G"
    command: "git cz ai"
    description: "generate commit message"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
